import { ThemeProvider } from "@/providers/theme-provider"
import './globals.css'
import { Toaster } from '@/components/ui/toaster';
import Header from "@/components/header";

export const metadata = {
  title: 'My Website',
  description: 'Generated by create next app',
}

export const dynamic = "force-dynamic";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-background flex flex-col items-center text-foreground">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header/>
          <main className="m-3">
              {children}
          </main>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  )
}
