import Header from '@/components/Header';
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const dynamic = "force-dynamic";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-background flex flex-col items-center text-foreground">
        <Header/>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
